services:
  # 前端服务
  frontend:
    image: aitodofrontend2
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  # 后端服务
  backend:
#    build: ./backend
    image: backend
    ports:
      - "8080:8080"
    volumes:
      - ./config/config.yaml:/app/config/config.yaml
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-network

  # MySQL 服务
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mysql_data_volume:/var/lib/mysql
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost","-u","root", "-p123456"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network

    # Redis 服务
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data_volume:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network

# 定义数据卷
volumes:
  mysql_data_volume:
  redis_data_volume:

# 定义网络
networks:
  app-network: