env: development

database:
  host: 127.0.0.1
  port: 3306
  user: root
  password: 123456
  name: todo
#  max_open_conns: 25
#  max_idle_conns: 5
  conn_max_lifetime: 1h
#  ssl_mode: disable

sms:
  endpoint: "dysmsapi.aliyuncs.com"
  sign_name: "任务管理助手"
  template_code: "SMS_479865001"

redis:
  addr: "localhost:6379"
  password: ""
  db: 0